name: Trigger auto deployment for myfin-app-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/reverse_proxy_dev.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYFINAPPDEV_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.MYFINAPPDEV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYFINAPPDEV_REGISTRY_PASSWORD }}
          containerAppName: myfin-app-dev
          resourceGroup: MyFin-App-Dev
          imageToBuild: muhil18/myfin-app-dev:${{ github.sha }}
          

     

